name: Generate rss feeds

on:
  push:
  schedule:
    - cron: "*/15 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Generate rss (rarbg)
        run: |
          python ./rarbg/generate.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Apply automatic changes

          file_pattern: ./*.xml

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: .

          # Optional: Skip internal call to `git fetch`
          skip_fetch: true

